#!/usr/bin/env python3
"""Script to generate a Markdown table of links from a Docusaurus `sidebar.json`.

Usage examples:
  python src/mddocs/gen_index_md_table.py \
    --sidebar docs-md/docs/reference/sidebar.json \
    --docs-root docs-md/docs \
    > sidebar_links.md

This script generates a Markdown index file with table of links from a `sidebar.json` generated by `pydoc-markdown docusaurus`.
"""
from __future__ import annotations

import argparse
import json
import sys
import os
import re
from pathlib import Path
from typing import Optional, List, Any
from enum import Enum


def load_sidebar(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def collect_doc_ids(node: Any) -> List[str]:
    ids: List[str] = []
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "items":
                if isinstance(v, list):
                    for it in v:
                        ids.extend(collect_doc_ids(it))
            #else:
            #    ids.extend(collect_doc_ids(v))
    elif isinstance(node, list):
        for it in node:
            ids.extend(collect_doc_ids(it))
    elif isinstance(node, str):
        ids.append(node)
    return ids


def find_file(docs_dir: Path, doc_id: str) -> Optional[Path]:
    # Try direct md, then index.md inside folder
    candidate = docs_dir / (doc_id + ".md")
    if candidate.exists():
        return candidate
    candidate = docs_dir / doc_id / "index.md"
    if candidate.exists():
        return candidate
    # Try without any leading ./ or / (sanitise)
    candidate = docs_dir / doc_id.lstrip("/")
    if candidate.exists():
        return candidate
    # Not found
    return None


def extract_title(path: Optional[Path]) -> Optional[str]:
    if path is None or not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    # YAML frontmatter
    if text.startswith("---"):
        parts = text.split("---")
        if len(parts) >= 3:
            fm = parts[1]
            for line in fm.splitlines():
                if line.strip().lower().startswith("title:"):
                    return line.split(":", 1)[1].strip().strip('"\'')
    # First level-1 header
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s.lstrip("# ").strip()
    # Fallback to filename stem
    return path.stem

class HeaderParseState(Enum):
    BEFORE_HEADER = 1
    IN_HEADER = 2
    AFTER_HEADER = 3

def get_first_md_doc_sentence(filepath):
    content_before_chapter = []
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            header_parse_state = HeaderParseState.BEFORE_HEADER
            for line in f:
                stripped = line.strip()
                # Check for header parsing
                if stripped == "---":
                    if header_parse_state == HeaderParseState.BEFORE_HEADER:
                        header_parse_state = HeaderParseState.IN_HEADER
                        continue
                    elif header_parse_state == HeaderParseState.IN_HEADER:
                        header_parse_state = HeaderParseState.AFTER_HEADER
                        continue
                elif header_parse_state == HeaderParseState.IN_HEADER:
                    continue
                # Check for chapter marker (header)
                if stripped.startswith('#'):
                    break
                content_before_chapter.append(line)
    except FileNotFoundError:
        return "Error: File not found."

    # Join lines and strip leading/trailing whitespace
    text = "".join(content_before_chapter).strip()
    
    if not text:
        return ""

    # Normalize whitespace (replace newlines with spaces)
    text = " ".join(text.split())

    # Regex to find the first sentence.
    # It looks for non-greedy characters until a punctuation mark (. ! ?)
    # followed by a whitespace or end of string.
    # Note: This is a basic implementation and might fail on abbreviations like "Mr.".
    match = re.search(r'(.*?[.!?])(\s|$)', text)
    if match:
        return match.group(1)
    else:
        # If no sentence delimiter is found, return the text as is.
        return text

def generate_table(sidebar_path: Path, docs_dir: Path) -> str:
    data = load_sidebar(sidebar_path)
    ids = collect_doc_ids(data)
    lines = ["| Page | Info |", "| --- | --- |"]
    seen = set()
    for doc_id in ids:
        if doc_id in seen:
            continue
        seen.add(doc_id)
        fp = find_file(docs_dir, doc_id)
        title = extract_title(fp) or Path(doc_id).name
        info = get_first_md_doc_sentence(fp)
        if fp:
            rel = os.path.relpath(fp, docs_dir)
            rel = rel.replace(os.sep, "/")
        else:
            # If file not found, link to the doc id as a path
            rel = (doc_id + ".md").replace(os.sep, "/")
        lines.append(f"| [{title}]({rel}) | {info} |")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description="Generate markdown table from sidebar.json")
    p.add_argument("--sidebar", required=True, help="Path to sidebar.json")
    p.add_argument("--docs-dir", required=True, help="Docs generated directory")
    p.add_argument("--out", help="Output file (defaults to stdout)")
    args = p.parse_args()

    sidebar = Path(args.sidebar)
    docs_dir = Path(args.docs_dir)

    if not sidebar.exists():
        raise SystemExit(f"sidebar file not found: {sidebar}")
    if not docs_dir.exists():
        raise SystemExit(f"docs dir not found: {docs_dir}")

    md = generate_table(sidebar, docs_dir)

    if args.out:
        Path(args.out).write_text(md, encoding="utf-8")
    else:
        print(md)
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
